### PR TITLE
GWD interstitial reorganization

### PR DESCRIPTION
**Pull request by grantfirl**
add GFS_GWD_generic_post scheme to SDFs using default GWD and substitute GFS_GWD_generic_pre,post for drag_suite_pre,post

### CODE REVIEW

**Comment by grantfirl** [comment]
This was tested on hera/intel using rt.conf. 

[rt_full_gwd_interstitial_reorg.log](https://github.com/NCAR/fv3atm/files/3815799/rt_full_gwd_interstitial_reorg.log)

**Comment by climbfuji** [comment]
@grantfirl rt.conf doesn't test the drag suite - has this been done using `rt_ccpp_gsd.conf`?

**Comment by grantfirl** [comment]
No, I didn't run rt_ccpp_gsd.conf. You're right that It probably should be run though.

**Comment by climbfuji** [comment]
Can you do that, please? You probably still have the source code ready to go on hera, and rt_ccpp_gsd.conf is short. Note that the dynamic verify test of the drag suite against the static create will fail (but the static verify test will pass).

**Comment by grantfirl** [comment]
OK, rt_ccpp_gsd.conf in create mode is running now...

**Comment by grantfirl** [comment]
rt_ccpp_gsd passed except for the expected dynamic drag suite test:

[rt_ccpp_gsd_create.log](https://github.com/NCAR/fv3atm/files/3849219/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NCAR/fv3atm/files/3849221/rt_ccpp_gsd_verify.log)

**Pull request merged**
